url: ''

title: AM 02:00

template: am0200

plugins:
  - script.js
  - acyort-server

public: docs

repos:
  - LoeiFy/am0200
  - acyortjs/acyort
  - fratercula/nycticorax
  - LoeiFy/Mirror
  - fratercula/pavane
  - fratercula/falco
  - LoeiFy/Diaspora
