url: https://am0200.com

template: am0200

plugins:
  - script.js
  - acyort-server

public: docs

repos:
  - acyortjs/acyort
  # - fratercula/nycticorax
  # - LoeiFy/Mirror
  # - fratercula/pavane
  # - fratercula/falco
  # - LoeiFy/Diaspora
